# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :demo do|options|
    branch = options[:branch]
    
    schemeName = "Demoz"
    export_method = "enterprise"
    
    api_key = "df0ed4aa84c5014612853e7cdb349a8c"
    user_key = "d15e50f3e8471965296291408494f532"
    
    puts "请输入版本描述："
    desc = STDIN.gets
    
    puts "开始打包 #{schemeName}"
    # 开始打包
gym(
    #指定scheme的名字
    scheme: "#{schemeName}",
    #输出的ipa名称
    output_name:"#{schemeName}",
    # 是否清空以前的编译信息 true：是
    clean:true,
    # 指定打包方式，Release 或者 Debug
    configuration:"Release",
    # 指定打包所使用的输出方式，目前支持app-store, package, ad-hoc, enterprise, development
    export_method:"#{export_method}",
    #指定输出文件夹，这里会保存我们最后生成的ipa文件，也就是存到了我们上面提到的fastlane文件夹中的build文件夹中
    output_directory:"./fastlane/build",
)

#puts "开始上传到蒲公英"
#开始上传ipa到蒲公英，这里用的是蒲公英提供的插件
#update_description代表更新信息，password代表安装密码
#pgyer(update_description: "#{desc}", api_key: "#{api_key}", user_key: "#{user_key}", password: "1111", install_type: "2")

puts "开始上传到fir"

#开始上传ipa到fir
fir(api_token: "c4e3c8fc97937246c3e792b2619d3425", apk_path: "./fastlane/build/#{schemeName}.ipa", changelog: "#{desc}")



#在上传完ipa后，打开ipa的存放文件夹，起到提示上传完成的作用
system "open ../fastlane/build"
    
    
  end
end
